### ISSUE TITLE
Regarding the issue of server archive format conversion

### ISSUE THREAD

**Issue by yizexiaomu** [CesiumMC/cesium-fabric#11]
I have noticed that you added archive format conversion on the server to the mod last month, but I still haven't seen archive conversion on the server's configuration file

**Comment by yamayaki1** [comment]
I’ll create an wiki entry in the following days. To invoke the convention progress on the server you append the flag `--cesiumConvertToAnvil` or `--cesiumConvertToCesium` to the server’s command line (e.g. `java -Xmx4G -jar fabric_server.jar --cesiumConvertToCesium`).

**Comment by yamayaki1** [comment]
A wiki entry has been created.
