### ISSUE TITLE
1.21 Unable to convert server save

### ISSUE THREAD

**Issue by yizexiaomu** [CesiumMC/cesium-fabric#12]
When converting the server save to the client on 1.21, the conversion was completed in an instant. Upon entering the game save, it was found to be a new and unrelated database save created by Cesium. I tried to modify the zstd level but it had no effect. The vanilla save size is 33G, which may be very useful information for you. If you need me to provide any information or record a video, please feel free to ask me. I am more than willing to help you troubleshoot this issue

**Comment by yamayaki1** [comment]
Hello,

I’ve been busy the last weeks, so it’s taking some time to catch up.
I’d need the log file found in `.minecraft/logs/` after an attempted conversion. It should not contain any sensitive information except your Windows username in file paths, so you might want to censor those.

**Comment by yizexiaomu** [comment]
This is my path:    D:\minecraft\versions\1.21-Fabric 0.15.11    this is my log,
[latest.log](https://github.com/user-attachments/files/16402025/latest.log)

**Comment by yizexiaomu** [comment]
> This is my path: D:\minecraft\versions\1.21-Fabric 0.15.11 this is my log, [latest.log](https://github.com/user-attachments/files/16402025/latest.log)

I have changed the path name to D: \ minecraft \ versions \ 121, but the error is still the same

**Comment by yizexiaomu** [comment]
> This is my path: D:\minecraft\versions\1.21-Fabric 0.15.11 this is my log, [latest.log](https://github.com/user-attachments/files/16402025/latest.log)

I have changed the path name toD:\minecraft\versions\121, but the error is still the same

**Comment by yizexiaomu** [comment]
After multiple tests and analysis, I found that after removing player data, conversion can proceed normally. I am not sure what caused this

**Comment by yamayaki1** [comment]
If you could use this build ([issue/12@44820e7](https://github.com/yamayaki1/cesium-fabric/actions/runs/10132236450/artifacts/1748183758)) and send a new log file that would be awesome. Please also re-add the player data.

From the looks of it, there seems to be a file (or files) in the `playerdata` directory that the converter is not happy about. Those files will now be logged. Once I know what files those are I can make the converter ignore those.

**Comment by yizexiaomu** [comment]
[latest.log](https://github.com/user-attachments/files/16404022/latest.log)

**Comment by yamayaki1** [comment]
This build ([issue/12@94ca5a0](https://github.com/yamayaki1/cesium-fabric/actions/runs/10132488966)) should fix the issue. There are some stale files in your `playerdata` directory (e.g. `4474631a-fbeb-4008-8ee8-1b14d9ffd9b9-5066197268282293337.dat`) that are now being ignored.

**Comment by yizexiaomu** [comment]
awesome! it worked, thank you for solving the problem!
[latest.log](https://github.com/user-attachments/files/16404089/latest.log)
