### ISSUE TITLE
Will this MOD increase read and write speeds

### ISSUE THREAD

**Issue by aa846301** [CesiumMC/cesium-fabric#14]
Will this MOD increase read and write speeds?

Currently, it maintains atomicity, so do I need to frequently stop the server to allow it to save?

**Comment by yamayaki1** [comment]
Hello,

I have not done any benchmarks on how read/ write speeds compare to vanilla. That might be an interesting thing to do in the future. The difference should be negligible though, if there is any.

As for your second question, no, you do not have to stop the server to allow it to save. It will do that frequently while running just fine.
