### ISSUE TITLE
Incompatibility with owo-lib

### ISSUE THREAD

**Issue by cntrik** [CesiumMC/cesium-fabric#2]
Crash on world creation
Cesium 0.1.5 & [owo-lib](https://modrinth.com/mod/owo-lib) 0.11.1
1. Start game
2. Make new world
3. [Crash Report](https://gist.github.com/Afrocntrik/2db30037a48ac15f6e9fdb9c26180dd1)

**Comment by yamayaki1** [comment]
Thanks for the report. I’ll try to release a fixed version as soon as possible.

**Comment by yamayaki1** [comment]
Should be fixed with Cesium 0.1.6.
