### ISSUE TITLE
Add option to convert world on the server

### ISSUE THREAD

**Issue by fennecr** [CesiumMC/cesium-fabric#5]
Description mentions only how to convert between anvil and cesium for client worlds. How would one go about converting an anvil world to a cesium one in a server environment?

**Comment by yamayaki1** [comment]
There is currently no way to convert an anvil world from or to the cesium format on the server. I might add a startup flag in a later release. The only option as of right now is to download the world to your computer, convert it using the client and then upload it to the server again.

Sorry for the inconvenience.
