### ISSUE TITLE
Add option to disable compression

### ISSUE THREAD

**Issue by obj-obj** [CesiumMC/cesium-fabric#7]
I use `zstd:9` full disk compression, which makes the compression optimization in this mod irrelevant to me.

**Comment by yamayaki1** [comment]
## Use on your own risk! Create a backup before using this experimental version!
I went ahead and made an **experimental** branch of Cesium that supports disabling data compression. Disabling compression can be achieved by setting the `compresssion.level` option to `0`. Please note that once you loaded your world with this experimental branch, you **can no longer use the official version of Cesium**, as the data format used in the experimental branch is unknown to the official release.

This limitation can be worked around by converting the world in the following order: `Cesium to Anvil (Experimental Branch)` --> `Anvil to Cesium (Stable Branch)`.

If you want to try this **experiment** out, you can download the latest artifact from [GitHub Actions (test/disable-compression)](https://github.com/yamayaki1/cesium-fabric/actions?query=branch%3Atest%2Fdisable-compression).

**Comment by obj-obj** [comment]
@yamayaki1 does https://github.com/yamayaki1/cesium-fabric/commit/f96c26708de87e5dd12260a93a4e053485af6cda close this issue?

**Comment by yamayaki1** [comment]
Well, this was originally not supposed to land in the main branch, but here I am, pushing commits to the wrong repositories. The linked commit *does* close this issue, so ...

There's no real upgrade path from the artifact I sent in March, it uses a different data structure, so you'd have to do the following:
1. Boot up the version of Cesium I linked in March and convert the world to the Vanilla format.
2.  Boot up any of the newer versions of Cesium, disable compression and then convert back to Cesium.

The latest release should make this process a bit faster.
