### ISSUE TITLE
Config to make new worlds in cesium format

### ISSUE THREAD

**Issue by AlexanderwithaA** [CesiumMC/cesium-fabric#8]
As the title says, I want to use this in an experimental performance modpack and being able to configure new worlds to use this format by default would be a wonderful option to have.
I’m using 1.20.4 btw

**Comment by yamayaki1** [comment]
When you have the mod installed, all worlds will use Cesium's format instead of the vanilla one. No further configuration required.

**Comment by AlexanderwithaA** [comment]
That’s good to know. I didn’t see that anywhere so thanks.
